openapi: 3.0.3
info:
  version: 1.0.0
  title: fispan.com
  contact:
    email: sales@fispan.com
    url: 'https://fispan.com/contact-us/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://fispan.com/wp-content/uploads/2019/09/Screenshot.png'
  description: >-
    # Introduction

    ## The Future Of Commercial Banking Is Integrated

    FISPAN makes it simple for banks to remove friction and provide the banking
    experience of the future to commercial clients. We turn banking services
    into branded banking experiences embedded within the ERP and accounting
    software your clients rely on to run their business.
x-tagGroups:
  - name: Authentication
    tags:
      - OAuth Token
  - name: Vendor
    tags:
      - Vendor
tags:
  - name: OAuth Token
    description: Authenticates the user and retrieves a valid OAuth2 Bearer Token.
  - name: Vendor
    description: Manages vendors in FI.SPAN platform.
servers:
  - url: 'https://dev1.fispan.cloud'
  - url: 'http://localhost'
paths:
  /accounts/oauth/token:
    post:
      tags:
        - OAuth Token
      summary: Authenticates users on FI.SPAN
      description: >-
        Doing the authentication requires that the grant_type is sent as a
        parameter. The possible grant types are:

        * `client_credentials`: Used for service providers and end users.

        * `password`: Used for admin users.
      operationId: getOAuthToken
      security:
        - basicAuth: []
      parameters:
        - $ref: '#/components/parameters/accounts_oauth_token_grant_type'
        - $ref: '#/components/parameters/accounts_oauth_token_username'
        - $ref: '#/components/parameters/accounts_oauth_token_password'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_token'
              example:
                access_token: 261e80be-58e1-4ecf-8f24-c1cc3f8ff168
                token_type: bearer
                expires_in: 1800
                scope: read write
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                error: unsupported_grant_type
                error_description: Unsupported grant type
        '401':
          description: Unauthorized Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                error: unauthorized
                error_description: Full authentication is required to access this resource
  /api/config-api/vendors:
    get:
      tags:
        - Vendor
      summary: Lists paged FI.SPAN vendors.
      description: >-
        This API will search FI.SPAN vendors associated with the logged in
        client or service provider and return

        all the vendors found paginated. The default page size is 20. The page
        number and its size can be changed

        using the optional parameter below

        * `page`: The page number to be returned.

        * `size`: The size of the page to be returned.
      operationId: listVendors
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/page_query_parameter'
        - $ref: '#/components/parameters/size_query_parameter'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/array_of_vendors'
              example:
                - id: c9802206-1785-43a4-97e5-aaa3e69651f8
                  externalId: null
                  subjectOfPayment:
                    externalId: vendor_external_id
                    type: INDIVIDUAL
                    taxId: '123456789'
                    principleOfficerDoB: '2001-07-21'
                    ssn: '1234567890'
                    availablePaymentMethods:
                      - ECHECK
                      - ACH
                    registeredPaymentMethods:
                      - type: ECheck
                        default: true
                        bankAccount:
                          id: 947fed2f-ec8b-4df9-b24f-37b48667e21b
                          externalId: null
                          institutionNumber: '001'
                          transitNumber: '17895'
                          accountNumber: '3258974'
                          enabledProducts:
                            - PAYMENT
                            - RECEIVABLE
                            - REMITTANCE
                        email: email@email.com
                        name: Contact Name
                      - type: ACH
                        default: false
                        bankAccount:
                          id: 947fed2f-ec8b-4df9-b24f-37b48667e21b
                          externalId: null
                          institutionNumber: '001'
                          transitNumber: '17895'
                          accountNumber: '3258974'
                          enabledProducts:
                            - PAYMENT
                            - RECEIVABLE
                            - REMITTANCE
                    address:
                      externalId: null
                      streetName: Main Avenue
                      streetNumber: '125'
                      city: New York
                      stateProvince: NY
                      country: United States of America
                      postalCode: '95625'
                      line2: Close to Burger King
                      defaultFor:
                        - ECHECK
                        - ACH
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
  parameters:
    accounts_oauth_token_grant_type:
      name: grant_type
      in: query
      schema:
        type: string
        enum:
          - client_credentials
          - password
      required: true
      description: |
        The type of grant that will be used to authenticate the user.
        * `client_credentials` - OAuth2 client credentials flow.
        * `password` - OAuth2 password flow.
    accounts_oauth_token_username:
      name: username
      in: query
      schema:
        type: string
      required: false
      description: >-
        The username to be used to authenticate the user. Only valid on for
        grant_type `password`.
    accounts_oauth_token_password:
      name: password
      in: query
      schema:
        type: string
        format: password
      required: false
      description: >-
        The password to be used to authenticate the user. Only valid on for
        grant_type `password`.
    page_query_parameter:
      name: page
      in: query
      schema:
        type: integer
        minimum: 0
        multipleOf: 1
      required: false
      description: >-
        The page number to be returned. It goes from 0 to N, where N depends on
        the number of records.
    size_query_parameter:
      name: size
      in: query
      schema:
        type: integer
        minimum: 1
        multipleOf: 1
      required: false
      description: >-
        The number of records retrieved per page. Defaults to 20 and goes up to
        1000, even if

        it's set to a number greater than 1000.
  schemas:
    auth_token:
      type: object
      properties:
        access_token:
          description: The access token in GUID format.
          type: string
          minLength: 36
          maxLength: 36
          example: 261e80be-58e1-4ecf-8f24-c1cc3f8ff168
        token_type:
          description: The type of the token.
          type: string
          example: bearer
        expires_in:
          description: The duration in seconds of the token before it expires.
          type: integer
          example: 1800
        scope:
          description: The scope of the generated token.
          type: string
          example: read write
    error:
      type: object
      properties:
        error:
          description: The name of the error.
          type: string
          example: unsupported_grant_type
        error_description:
          description: The description of the error
          type: string
          example: Unsupported grant type
    payment_type:
      type: string
      enum:
        - ACH
        - CHECK
        - CPA
        - EMT
        - RTP
        - VCC
        - POSITIVE_PAY
        - WIRE
        - SEPA
        - BACS
        - INTERNATIONAL_WIRE
        - INTERNATIONAL_ACH
        - ECHECK
        - A2A_TRANSFER
      description: The possible available payment methods.
    erp_provider:
      type: string
      enum:
        - NONE
        - UNKNOWN
        - DUMMY
        - FRESHBOOKS
        - INTACCT
        - MYOB
        - NAVISION
        - NETSUITE
        - ORACLE
        - QUICKBOOKS
        - QUICKBOOKS_DESKTOP
        - SAGE50
        - SAP
        - MS_BUSINESS_CENTRAL
        - MS_BUSINESS_CENTRAL_ONPREM_14
        - TEST_ERP
        - XERO
        - ACUMATICA
      description: The erp's provider.
      example: NETSUITE
    erp_id:
      type: object
      properties:
        id:
          description: The internal idenification for the ERP.
          type: string
          example: 7029706a-40cf-4d39-a06a-5ca5eb9361da
        erpProvider:
          $ref: '#/components/schemas/erp_provider'
    product_type:
      type: string
      enum:
        - PAYMENT
        - RECEIVABLE
        - LENDING
        - BANK_ACCOUNT_INFO
        - VALIDATION
        - FX_INFO
        - ENRICHMENT
        - REMITTANCE
    bank_account:
      type: object
      description: The bank account associated with the payment methods.
      properties:
        id:
          description: The bank account identification
          type: string
          example: 947fed2f-ec8b-4df9-b24f-37b48667e21b
        externalId:
          description: Bank specific account id
          type: string
          nullable: true
          example: bank_account_external_id
        erpIds:
          description: The ERP providers for the bank account
          type: array
          items:
            $ref: '#/components/schemas/erp_id'
          minItems: 0
          example:
            - id: 7029706a-40cf-4d39-a06a-5ca5eb9361da
              erpProvider: NETSUITE
        accountLabel:
          description: A label to help identifying the account.
          type: string
          nullable: true
          example: Cheque
        accountHolderName:
          description: >-
            Legal entity or subsidiary name. Is used to override Client's name
            in payables.
          type: string
          nullable: true
          example: John Smith
        bankName:
          description: The name of the bank
          type: string
          nullable: true
          example: Bank of America
        institutionNumber:
          description: >-
            The number of the institution. We can also call it the bank number.
            Required for Canadian bank accounts
          type: string
          nullable: true
          example: '001'
        transitNumber:
          description: The branch identification. Required for Canadian bank accounts
          type: string
          nullable: true
          example: '1758'
        routingNumber:
          description: Required for US bank accounts. This field is masked.
          type: string
          nullable: true
          example: '********'
        accountNumber:
          description: >-
            Required for both Canadian and US bank accounts. This field is
            masked.
          type: string
          nullable: true
          example: '******7395'
        enabledProducts:
          description: The products that are enabled for the given bank account.
          type: array
          items:
            $ref: '#/components/schemas/product_type'
    base_payment_method:
      type: object
      properties:
        type:
          description: The type of the payment.
          type: string
          example: ACH
        default:
          description: Indicates if the given payment method is to be used by default.
          type: boolean
          example: true
        bankAccount:
          $ref: '#/components/schemas/bank_account'
    ACH:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
    Check:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
    CPA:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
    ECheck:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
        - type: object
          properties:
            email:
              description: The email associated with the EMT payment method.
              type: string
              format: email
            name:
              description: The name associated with the EMT payment method.
              type: string
    EMT:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
        - type: object
          properties:
            email:
              description: The email associated with the EMT payment method.
              type: string
              format: email
    WIRE:
      allOf:
        - $ref: '#/components/schemas/base_payment_method'
    address_type:
      type: string
      enum:
        - PAYMENT
        - CONTACT
    address:
      type: object
      description: The address associated with the subject of payment.
      deprecated: true
      properties:
        externalId:
          description: The external identification for the address.
          type: string
          nullable: true
          example: address_external_id
        streetName:
          description: The name of the street.
          type: string
          nullable: true
          example: Main Avenue
        streetNumber:
          description: The property number on the given street.
          type: string
          nullable: true
          example: '125'
        city:
          description: The city where the address is located
          type: string
          nullable: true
          example: New York
        stateProvince:
          description: The state or province where the address is located.
          type: string
          nullable: true
          example: NY
        country:
          description: The country where the address is located.
          type: string
          nullable: true
          example: United States of America
        postalCode:
          description: The address' postal code.
          type: string
          nullable: true
          example: '95625'
        line1:
          description: The line 1 for the address.
          type: string
          nullable: true
          deprecated: true
          example: Suite 501
        line2:
          description: The line 1 for the address.
          type: string
          nullable: true
          example: Close to the Burger King
        types:
          description: The types of the address.
          type: array
          items:
            $ref: '#/components/schemas/address_type'
          minItems: 0
          maxItems: 2
        defaultFor:
          description: >-
            Indicates what payment types will use this address as their default
            address
          type: array
          items:
            $ref: '#/components/schemas/payment_type'
          minItems: 0
          maxItems: 14
      example:
        externalId: null
        streetName: Main Avenue
        streetNumber: 125
        city: New York
        stateProvince: NY
        country: United States of America
        postalCode: '95825'
        line1: null
        line2: Suite 501
        types: []
        defaultFor:
          - ACH
    subject_of_payment:
      type: object
      properties:
        externalId:
          description: The external identification for the subject of payment.
          type: string
          example: vendor_external_id
          nullable: true
        type:
          description: The subject of payment's type.
          type: string
          enum:
            - INDIVIDUAL
            - COMPANY
          nullable: true
          example: INDIVIDUAL
        taxId:
          description: Taxation identification number for the company.
          type: string
          nullable: true
          example: 123456789
          minLength: 9
          maxLength: 9
        principleOfficerDoB:
          description: Date of Birth is of principle officer within the organization.
          type: string
          format: date
          nullable: true
          example: '2001-07-21'
        ssn:
          description: >-
            SSN is of principle officer within the organization. SSN length is
            either 4 or 10 characters long
          type: string
          nullable: true
          minLength: 4
          maxLength: 10
          example: '1234567890'
        availablePaymentMethods:
          type: array
          items:
            $ref: '#/components/schemas/payment_type'
        registeredPaymentMethods:
          description: The registered payment methods within the company.
          type: array
          deprecated: true
          items:
            oneOf:
              - $ref: '#/components/schemas/ACH'
              - $ref: '#/components/schemas/Check'
              - $ref: '#/components/schemas/CPA'
              - $ref: '#/components/schemas/ECheck'
              - $ref: '#/components/schemas/EMT'
              - $ref: '#/components/schemas/WIRE'
        address:
          $ref: '#/components/schemas/address'
    vendor:
      type: object
      properties:
        id:
          description: The vendor id in GUID format.
          type: string
          minLength: 36
          maxLength: 36
          example: c9802206-1785-43a4-97e5-aaa3e69651f8
        externalId:
          description: The vendor's external identification.
          type: string
          nullable: true
          example: vendor_external_id
        subjectOfPayment:
          $ref: '#/components/schemas/subject_of_payment'
    array_of_vendors:
      type: array
      items:
        $ref: '#/components/schemas/vendor'
      minItems: 0
